name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      # Compila sin necesitar gradlew en el repo
      - name: Build Debug APK (Gradle)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: TamagotchiLaMichoacana
          arguments: |
            -Dorg.gradle.daemon=false
            -Dorg.gradle.vfs.watch=false
            -Dorg.gradle.jvmargs=-Xmx2g
            clean assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: TamagotchiLaMichoacana/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
